name: Cleanup Temporary Branches After PR Merge or Close

on:
  pull_request:
    types:
      - closed  # Trigger the workflow when the PR is closed (merged or rejected)
permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event.pull_request.state == 'closed'  # Check for merge or closed state

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Run delete branch
        run: |
          git branch | grep 'review-artifact' | xargs git branch -d
