name: LateX to PDF for PR

on:
    pull_request:
permissions:
  contents: write
  pull-requests: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: editorial.tex
      - name: Push PDF to Temporary Branch
        run: |
          TEMP_BRANCH="review-artifact-${{ github.event.pull_request.number }}"
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git checkout -b $TEMP_BRANCH
          git add editorial.pdf
          git commit -m "Add generated PDF for review"
          git push -f origin $TEMP_BRANCH
      - name: Comment on PR with File Link
        uses: actions/github-script@v6
        with:
          script: |
            const branchName = `review-artifact-${{ github.event.pull_request.number }}`
            const fileUrl = `https://github.com/${{ github.repository }}/blob/${branchName}/editorial.pdf`
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `The generated PDF for review is available on the branch [${branchName}](${fileUrl}). You can view it [here](${fileUrl}).`
            });
